title: "{ Yura &amp; Viki &#8211; Welcome to our space }"
excerpt_separator: <!--more-->
plugins:
  - jekyll-assets
assets:
  sources: 
    - assets/css
    - assets/images
    - assets/js
  digest: false
collections:
  category:
    output: true
    permalink: /:collection/:name
defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
exclude:
  - .asset-cache
  - .history
